package com.ramiart.admin.tuition.infrastructure;

import com.ramiart.admin.tuition.application.*;
import com.ramiart.admin.tuition.application.StudentTuitionAssignmentModels.*;
import com.ramiart.admin.tuition.application.StudentTuitionAssignmentRepository.*;
import java.time.LocalDate;
import java.util.*;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.stereotype.Repository;

@Repository
public class JdbcStudentTuitionAssignmentRepository implements StudentTuitionAssignmentRepository {
    private final JdbcClient jdbc;
    public JdbcStudentTuitionAssignmentRepository(JdbcClient jdbc){this.jdbc=jdbc;}
    @Override public Optional<Student> student(UUID id,boolean lock){return jdbc.sql("select id,student_name,status from student where id=:id"+(lock?" for update":"")).param("id",id).query((r,n)->new Student(r.getObject("id",UUID.class),r.getString("student_name"),r.getString("status"))).optional();}
    @Override public int scheduleCount(UUID id,LocalDate date){return jdbc.sql("select count(distinct a.schedule_slot_id) from student_schedule_assignment a join schedule_slot s on s.id=a.schedule_slot_id and s.status='ACTIVE' where a.student_id=:id and :date between a.effective_from and coalesce(a.effective_to,'infinity'::date)").param("id",id).param("date",date).query(Integer.class).single();}
    @Override public List<PolicyOption> policyOptions(LocalDate date,int count){return jdbc.sql("select i.id,p.year,p.revision,i.lesson_count_per_week,i.monthly_amount,p.default_due_day from tuition_policy_item i join tuition_policy p on p.id=i.tuition_policy_id where p.status='PUBLISHED' and p.year=:year and i.lesson_count_per_week=:count order by p.revision desc").param("year",date.getYear()).param("count",count).query((r,n)->new PolicyOption(r.getObject("id",UUID.class),r.getInt("year"),r.getInt("revision"),r.getInt("lesson_count_per_week"),r.getLong("monthly_amount"),r.getInt("default_due_day"))).list();}
    @Override public List<Assignment> assignments(UUID student){return jdbc.sql(select()+" where a.student_id=:student order by a.effective_from").param("student",student).query(this::map).list();}
    @Override public Optional<Assignment> assignment(UUID id,boolean lock){return jdbc.sql(select()+" where a.id=:id"+(lock?" for update of a":"")).param("id",id).query(this::map).optional();}
    @Override public boolean policyItemPublished(UUID id){return jdbc.sql("select exists(select 1 from tuition_policy_item i join tuition_policy p on p.id=i.tuition_policy_id where i.id=:id and p.status='PUBLISHED')").param("id",id).query(Boolean.class).single();}
    @Override public Optional<Integer> policyItemCount(UUID id){return jdbc.sql("select i.lesson_count_per_week from tuition_policy_item i join tuition_policy p on p.id=i.tuition_policy_id where i.id=:id and p.status='PUBLISHED'").param("id",id).query(Integer.class).optional();}
    @Override public List<Assignment> overlaps(UUID student,LocalDate from,LocalDate to,UUID except){return jdbc.sql(select()+" where a.student_id=:student and (cast(:except as uuid) is null or a.id<>cast(:except as uuid)) and daterange(a.effective_from,coalesce(a.effective_to,'infinity'::date),'[]') && daterange(:from,coalesce(:to,'infinity'::date),'[]') order by a.effective_from").param("student",student).param("except",except).param("from",from).param("to",to).query(this::map).list();}
    @Override public UUID insert(UUID id,UUID student,Write w,UUID actor){jdbc.sql("insert into student_tuition_assignment(id,student_id,policy_item_id,effective_from,effective_to,override_amount,override_reason,created_by,updated_by) values(:id,:student,:item,:from,:to,:amount,:reason,:actor,:actor)").param("id",id).param("student",student).param("item",w.policyItemId()).param("from",w.effectiveFrom()).param("to",w.effectiveTo()).param("amount",w.overrideAmount()).param("reason",w.overrideReason()).param("actor",actor).update();return id;}
    @Override public int update(UUID id,Update w,String reason,UUID actor){return jdbc.sql("update student_tuition_assignment set effective_from=:from,effective_to=:to,override_amount=:amount,override_reason=:reason,updated_by=:actor,version=version+1 where id=:id and version=:version").param("from",w.effectiveFrom()).param("to",w.effectiveTo()).param("amount",w.overrideAmount()).param("reason",reason).param("actor",actor).param("id",id).param("version",w.version()).update();}
    @Override public Claim claim(String scope,UUID key,String hash){int n=jdbc.sql("insert into idempotency_record(scope,idempotency_key,request_hash,state,expires_at) values(:scope,:key,:hash,'PROCESSING',statement_timestamp()+interval '24 hours') on conflict(scope,idempotency_key) do nothing").param("scope",scope).param("key",key).param("hash",hash).update();if(n==1)return new Claim(true,null);Object[] row=jdbc.sql("select request_hash,state,resource_id from idempotency_record where scope=:scope and idempotency_key=:key").param("scope",scope).param("key",key).query((r,i)->new Object[]{r.getString(1),r.getString(2),r.getObject(3,UUID.class)}).single();if(!hash.equals(row[0]))throw new StudentTuitionAssignmentException("IDEMPOTENCY_KEY_REUSED");if(!"COMPLETED".equals(row[1])||row[2]==null)throw new StudentTuitionAssignmentException("IDEMPOTENCY_IN_PROGRESS");return new Claim(false,(UUID)row[2]);}
    @Override public void complete(String scope,UUID key,UUID id,int status){jdbc.sql("update idempotency_record set state='COMPLETED',resource_id=:id,response_status=:status where scope=:scope and idempotency_key=:key").param("id",id).param("status",status).param("scope",scope).param("key",key).update();}
    private String select(){return "select a.id,a.student_id,p.id policy_id,a.policy_item_id,a.effective_from,a.effective_to,a.override_amount,a.override_reason,a.version,i.lesson_count_per_week,i.monthly_amount,p.year,p.revision,p.default_due_day,b.earliest_billed,b.latest_billed,coalesce(b.billing_count,0) billing_count from student_tuition_assignment a join tuition_policy_item i on i.id=a.policy_item_id join tuition_policy p on p.id=i.tuition_policy_id left join (select tuition_assignment_id,min(to_date(year_month||'-01','YYYY-MM-DD')) earliest_billed,max(to_date(year_month||'-01','YYYY-MM-DD')) latest_billed,count(*) billing_count from tuition_billing group by tuition_assignment_id) b on b.tuition_assignment_id=a.id";}
    private Assignment map(java.sql.ResultSet r,int row)throws java.sql.SQLException{java.math.BigDecimal amount=r.getBigDecimal("override_amount");return new Assignment(r.getObject("id",UUID.class),r.getObject("student_id",UUID.class),r.getObject("policy_id",UUID.class),r.getObject("policy_item_id",UUID.class),r.getObject("effective_from",LocalDate.class),r.getObject("effective_to",LocalDate.class),amount==null?null:amount.longValueExact(),r.getString("override_reason"),r.getLong("version"),r.getInt("lesson_count_per_week"),r.getLong("monthly_amount"),r.getInt("year"),r.getInt("revision"),r.getLong("default_due_day"),r.getObject("earliest_billed",LocalDate.class),r.getObject("latest_billed",LocalDate.class),r.getInt("billing_count"));}
}
