package com.ramiart.admin.galleryartwork.application;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.ramiart.admin.auth.application.AdminReauthenticationService;
import com.ramiart.admin.auth.application.AuditRecorder;
import com.ramiart.admin.auth.application.AuditRecorder.Event;
import static com.ramiart.admin.galleryartwork.application.GalleryArtworkModels.*;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.time.Clock;
import java.util.*;
import org.springframework.security.core.Authentication;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Isolation;
import org.springframework.transaction.annotation.Transactional;

@Service
public class GalleryArtworkService {
    public record RequestMetadata(String requestId,String ipAddress,String userAgent){}
    private final GalleryArtworkRepository repo;private final AdminReauthenticationService reauth;private final AuditRecorder audit;private final Clock clock;private final ObjectMapper mapper;
    public GalleryArtworkService(GalleryArtworkRepository repo,AdminReauthenticationService reauth,AuditRecorder audit,Clock clock,ObjectMapper mapper){this.repo=repo;this.reauth=reauth;this.audit=audit;this.clock=clock;this.mapper=mapper;}
    @Transactional(readOnly=true,isolation=Isolation.REPEATABLE_READ)
    public Page list(String keyword,List<UUID> courses,List<String> states,String featured,String sort,int page,int size,Authentication auth){require(auth,"GALLERY_READ");if(page<0||!Set.of(10,20,50).contains(size)||keyword!=null&&!keyword.isBlank()&&(keyword.trim().length()<2||keyword.trim().length()>50)||!Set.of("ALL","FEATURED","NOT_FEATURED").contains(featured)||!Set.of("UPDATED_DESC","PUBLISHED_DESC","TITLE_ASC","FEATURED_ORDER_ASC").contains(sort))throw new GalleryArtworkException("VALIDATION_ERROR");Page result=repo.list(keyword==null?null:keyword.trim(),courses,states,featured,sort,page,size);boolean canEdit=has(auth,"GALLERY_WRITE");return new Page(result.items().stream().map(x->new ListItem(x.artworkId(),x.title(),x.course(),x.medium(),x.media(),x.published(),x.draft(),canEdit?List.of("VIEW","EDIT"):List.of("VIEW"))).toList(),result.page());}
    @Transactional(readOnly=true,isolation=Isolation.REPEATABLE_READ)
    public Detail detail(UUID artwork,String mode,Authentication auth){require(auth,"GALLERY_READ");if(!Set.of("draft","published").contains(mode))throw new GalleryArtworkException("VALIDATION_ERROR");Stored d=repo.find(artwork,"DRAFT").orElse(null),p=repo.find(artwork,"PUBLISHED").orElse(null);Stored current=d==null?p:d;if(current==null)throw new GalleryArtworkException("GALLERY_NOT_FOUND");return detail(artwork,current,d,p,d!=null,d==null?null:d.id(),auth);}
    @Transactional public Mutation<Detail> create(Content content,UUID key,Authentication auth,RequestMetadata meta){UUID actor=require(auth,"GALLERY_WRITE");Content c=normalize(content);validate(c,false);if(c.consentExemptionReason()!=null)throw new GalleryArtworkException("GALLERY_REAUTH_REQUIRED");UUID artwork=UUID.randomUUID();String scope=actor+":GALLERY_CREATE";String hash=hash("POST:/api/admin/gallery-artworks:"+canonical(c));var claim=repo.claim(scope,key,hash);if(!claim.claimed())return new Mutation<>(detailCurrent(claim.resourceId(),auth),true);UUID draft=repo.create(artwork,1,actor,c,null);repo.replaceReferences(draft,c.mediaAssetId());repo.complete(scope,key,artwork,201);event(actor,meta,"CREATE_DRAFT",draft,Map.of());return new Mutation<>(detailCurrent(artwork,auth),false);}
    @Transactional public Mutation<Detail> createDraft(UUID artwork,UUID key,Authentication auth,RequestMetadata meta){UUID actor=require(auth,"GALLERY_WRITE");Stored p=repo.find(artwork,"PUBLISHED").orElseThrow(()->new GalleryArtworkException("GALLERY_NOT_FOUND"));String scope=actor+":GALLERY_DRAFT:"+artwork;var claim=repo.claim(scope,key,hash("POST:/api/admin/gallery-artworks/"+artwork+"/drafts"));if(!claim.claimed())return new Mutation<>(detailCurrent(artwork,auth),true);if(repo.find(artwork,"DRAFT").isPresent())throw new GalleryArtworkException("GALLERY_DRAFT_EXISTS");Content c=content(p);UUID d=repo.create(artwork,repo.maxRevision(artwork)+1,actor,c,p.id());repo.replaceReferences(d,c.mediaAssetId());repo.complete(scope,key,d,201);event(actor,meta,"CREATE_DRAFT",d,Map.of("artworkId",artwork));return new Mutation<>(detailCurrent(artwork,auth),false);}
    @Transactional public Detail save(UUID artwork,UUID draftId,Write raw,Authentication auth,RequestMetadata meta){UUID actor=require(auth,"GALLERY_WRITE");Write w=normalize(raw);validate(w,false);if(w.consentExemptionReason()!=null||w.reauthToken()!=null)throw new GalleryArtworkException("GALLERY_REAUTH_REQUIRED");Stored d=repo.findRevision(draftId).orElseThrow(()->new GalleryArtworkException("GALLERY_NOT_FOUND"));if(!d.artworkId().equals(artwork)||!"DRAFT".equals(d.status()))throw new GalleryArtworkException("GALLERY_NOT_FOUND");String scope=actor+":GALLERY_UPDATE:"+draftId;String requestHash=hash("PUT:/api/admin/gallery-artworks/"+artwork+"/drafts/"+draftId+":"+canonical(w));UUID key=UUID.nameUUIDFromBytes(requestHash.getBytes(StandardCharsets.UTF_8));var claim=repo.claim(scope,key,requestHash);
        if(!claim.claimed())return detailCurrent(artwork,auth);if(d.version()!=w.version())throw new GalleryArtworkException("GALLERY_VERSION_CONFLICT");if(repo.update(draftId,w)!=1)throw new GalleryArtworkException("GALLERY_VERSION_CONFLICT");repo.replaceReferences(draftId,w.mediaAssetId());repo.complete(scope,key,draftId,200);event(actor,meta,"UPDATE_DRAFT",draftId,Map.of("version",w.version()+1));return detailCurrent(artwork,auth);}
    @Transactional(readOnly=true) public Preview preview(UUID artwork,UUID draftId,long version,Authentication auth){require(auth,"GALLERY_READ");Stored d=repo.findRevision(draftId).orElseThrow(()->new GalleryArtworkException("GALLERY_NOT_FOUND"));if(!d.artworkId().equals(artwork))throw new GalleryArtworkException("GALLERY_NOT_FOUND");if(d.version()!=version)throw new GalleryArtworkException("GALLERY_VERSION_CONFLICT");List<Placement> places=new ArrayList<>();places.add(new Placement("GALLERY_CARD",d.title(),d.imageUrl(),d.description(),d.altText()));places.add(new Placement("GALLERY_LIGHTBOX",d.title(),d.imageUrl(),d.description(),d.altText()));if(d.featured())places.add(new Placement("HOME_FEATURED",d.title(),d.imageUrl(),d.description(),d.altText()));return new Preview(places,artwork,version);}
    @Transactional public Mutation<Detail> publish(UUID artwork,PublicationRequest body,UUID key,String cookie,Authentication auth,RequestMetadata meta){UUID actor=require(auth,"GALLERY_PUBLISH");if(body==null||body.draftId()==null||body.draftVersion()==null)throw new GalleryArtworkException("VALIDATION_ERROR");String scope=actor+":GALLERY_PUBLISH:"+artwork;String hash=hash(body.toString());var claim=repo.claim(scope,key,hash);if(!claim.claimed())return new Mutation<>(detailCurrent(artwork,auth),true);Stored d=repo.findRevision(body.draftId()).orElseThrow(()->new GalleryArtworkException("GALLERY_NOT_FOUND"));if(!d.artworkId().equals(artwork)||!"DRAFT".equals(d.status()))throw new GalleryArtworkException("GALLERY_NOT_FOUND");if(d.version()!=body.draftVersion())throw new GalleryArtworkException("GALLERY_VERSION_CONFLICT");
        Content c=content(d);if(d.exemptionReason()!=null&&body.consentExemptionReason()==null)throw new GalleryArtworkException("GALLERY_REAUTH_REQUIRED");if(body.consentExemptionReason()!=null){if(!repo.owner(actor))throw new GalleryArtworkException("GALLERY_REAUTH_REQUIRED");String reason=body.consentExemptionReason().trim();if(reason.length()<5||reason.length()>300||body.reauthToken()==null)throw new GalleryArtworkException("GALLERY_REAUTH_REQUIRED");reauth.consume(body.reauthToken(),cookie,"GALLERY_PUBLISH_EXEMPTION",auth);c=new Content(c.title(),c.courseId(),c.audienceLabel(),c.medium(),c.description(),c.mediaAssetId(),c.altText(),null,reason,c.visible(),c.featured(),c.featuredOrder());}
        validate(c,true);if(c.visible()&&!repo.consentValid(c.studentConsentId())&&c.consentExemptionReason()==null)throw new GalleryArtworkException("GALLERY_CONSENT_REQUIRED");if(c.visible()&&c.featured()&&c.featuredOrder()==null)throw new GalleryArtworkException("GALLERY_FEATURED_ORDER_CONFLICT");repo.publish(artwork,d.id(),d.version(),actor,c);repo.complete(scope,key,d.id(),201);Stored p=repo.find(artwork,"PUBLISHED").orElseThrow();event(actor,meta,"PUBLISH",d.id(),Map.of("revision",p.revision()));return new Mutation<>(detailCurrent(artwork,auth),false);}
    @Transactional(readOnly=true,isolation=Isolation.REPEATABLE_READ) public PublicPage publicList(List<String> codes,Boolean featured,int page,int size){if(page<1||size<1||size>100)throw new GalleryArtworkException("VALIDATION_ERROR");List<PublicArtwork> items=repo.publicList(codes,featured,page-1,size);long total=repo.publicCount(codes,featured);return new PublicPage(items,new PageInfo(page,size,total,(int)Math.ceil(total/(double)size)));}
    @Transactional(readOnly=true) public ConsentPage consents(String keyword,int page,int size,Authentication auth){require(auth,"CONSENT_READ");if(page<0||size<1||size>50||keyword!=null&&keyword.trim().length()>50)throw new GalleryArtworkException("VALIDATION_ERROR");return new ConsentPage(repo.consentOptions(keyword,page,size));}
    private Detail detail(UUID artwork,Stored current,Stored d,Stored p,boolean editable,UUID draft){return detail(artwork,current,d,p,editable,draft,null);}
    private Detail detail(UUID artwork,Stored current,Stored d,Stored p,boolean editable,UUID draft,Authentication auth){Revision dr=d==null?null:revision(d),pr=p==null?null:revision(p);MediaAsset media=current.mediaAssetId()==null?null:new MediaAsset(current.mediaAssetId(),current.imageUrl(),current.fileName(),current.mimeType(),current.fileSize(),current.width(),current.height(),"READY",current.expiresAt());ConsentStatus consent=current.consentId()!=null?new ConsentStatus(current.consentStatus()==null?"MISSING":current.consentStatus(),current.maskedStudentLabel(),current.policyRevision()):current.exemptionReason()!=null?new ConsentStatus("EXEMPTED",null,null):null;boolean canEdit=editable&&(auth==null||has(auth,"GALLERY_WRITE"));List<String> actions=canEdit?has(auth,"GALLERY_PUBLISH")?List.of("SAVE","PREVIEW","PUBLISH"):List.of("SAVE","PREVIEW"):editable?List.of("PREVIEW","CREATE_DRAFT"):List.of("CREATE_DRAFT");return new Detail(artwork,d!=null?"DRAFT":p!=null?"PUBLISHED":"NONE",canEdit,dr,pr,media,consent,actions);}
    private Detail detailCurrent(UUID artwork,Authentication auth){Stored d=repo.find(artwork,"DRAFT").orElse(null),p=repo.find(artwork,"PUBLISHED").orElse(null);Stored current=d==null?p:d;if(current==null)throw new GalleryArtworkException("GALLERY_NOT_FOUND");return detail(artwork,current,d,p,d!=null,d==null?null:d.id(),auth);}
    private static Revision revision(Stored s){return new Revision(s.id(),s.revision(),s.version(),s.title(),s.courseId(),s.audienceLabel(),s.medium(),s.description(),s.mediaAssetId(),s.altText(),s.consentId(),s.exemptionReason(),s.visible(),s.featured(),s.featuredOrder(),publishable(s),s.updatedAt(),s.publishedAt());}
    private static boolean publishable(Stored s){return s.title()!=null&&s.courseId()!=null&&s.audienceLabel()!=null&&s.medium()!=null&&s.description()!=null&&s.mediaAssetId()!=null&&s.altText()!=null&&((s.consentId()!=null&&"ACTIVE".equals(s.consentStatus()))||s.exemptionReason()!=null);}
    private static Content content(Stored s){return new Content(s.title(),s.courseId(),s.audienceLabel(),s.medium(),s.description(),s.mediaAssetId(),s.altText(),s.consentId(),s.exemptionReason(),s.visible(),s.featured(),s.featuredOrder());}
    private static Content normalize(Content c){if(c==null)throw new GalleryArtworkException("VALIDATION_ERROR");return new Content(trim(c.title()),c.courseId(),trim(c.audienceLabel()),trim(c.medium()),trim(c.description()),c.mediaAssetId(),trim(c.altText()),c.studentConsentId(),trim(c.consentExemptionReason()),c.visible(),c.featured(),c.featuredOrder());}
    private static Write normalize(Write w){if(w==null)throw new GalleryArtworkException("VALIDATION_ERROR");return new Write(w.version(),trim(w.title()),w.courseId(),trim(w.audienceLabel()),trim(w.medium()),trim(w.description()),w.mediaAssetId(),trim(w.altText()),w.studentConsentId(),trim(w.consentExemptionReason()),w.visible(),w.featured(),w.featuredOrder(),w.reauthToken());}
    private void validate(Content c,boolean publish){validateFields(c.title(),c.courseId(),c.audienceLabel(),c.medium(),c.description(),c.mediaAssetId(),c.altText(),c.visible(),c.featured(),c.featuredOrder(),publish);}
    private void validate(Write w,boolean publish){if(w.version()==null)throw new GalleryArtworkException("VALIDATION_ERROR");validateFields(w.title(),w.courseId(),w.audienceLabel(),w.medium(),w.description(),w.mediaAssetId(),w.altText(),w.visible(),w.featured(),w.featuredOrder(),publish);}
    private void validateFields(String title,UUID course,String audience,String medium,String description,UUID asset,String alt,Boolean visible,Boolean featured,Integer order,boolean publish){if(visible==null||featured==null)throw new GalleryArtworkException("VALIDATION_ERROR");if(len(title,150)||len(audience,100)||len(medium,100)||len(description,1000)||len(alt,300))throw new GalleryArtworkException("VALIDATION_ERROR");if(Boolean.TRUE.equals(featured)&&(!Boolean.TRUE.equals(visible)||order==null||order<0))throw new GalleryArtworkException("GALLERY_FEATURED_ORDER_CONFLICT");if(!Boolean.TRUE.equals(featured)&&order!=null)throw new GalleryArtworkException("VALIDATION_ERROR");if(publish&&Boolean.TRUE.equals(visible)&&(blank(title)||course==null||blank(audience)||blank(medium)||blank(description)||asset==null||blank(alt)))throw new GalleryArtworkException("GALLERY_NOT_PUBLISHABLE");if(publish&&!Boolean.TRUE.equals(visible)&&(blank(title)||course==null))throw new GalleryArtworkException("GALLERY_NOT_PUBLISHABLE");if(description!=null&&(description.matches("(?s).*\\b[0-9]{2,4}[- ]?[0-9]{3,4}[- ]?[0-9]{4}\\b.*")||description.contains("@")))throw new GalleryArtworkException("VALIDATION_ERROR","description");}
    private static boolean len(String s,int n){return s!=null&&s.length()>n;}private static boolean blank(String s){return s==null||s.isBlank();}private static String trim(String s){if(s==null)return null;String v=s.trim();return v.isEmpty()?null:v;}
    private static UUID require(Authentication a,String permission){if(a==null||a.getAuthorities().stream().noneMatch(x->permission.equals(x.getAuthority())))throw new GalleryArtworkException("GALLERY_PERMISSION_DENIED");try{return UUID.fromString(a.getName());}catch(Exception e){throw new GalleryArtworkException("GALLERY_PERMISSION_DENIED");}}
    private static boolean has(Authentication a,String permission){return a!=null&&a.getAuthorities().stream().anyMatch(x->permission.equals(x.getAuthority()));}
    private String canonical(Object value){try{return mapper.writeValueAsString(value);}catch(Exception e){throw new IllegalStateException(e);}}
    private static String hash(String text){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(text.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}
    private void event(UUID actor,RequestMetadata m,String action,UUID id,Map<String,Object> data){audit.record(new Event(clock.instant(),m.requestId(),"MGT-GALLERY-EDIT","OPERATION","ADMIN",actor,null,action,"GALLERY_ARTWORK",id,"SUCCESS",null,m.ipAddress(),m.userAgent(),data));}
}
