package com.ramiart.admin.galleryartwork.infrastructure;

import com.ramiart.admin.galleryartwork.application.GalleryArtworkException;
import com.ramiart.admin.galleryartwork.application.GalleryArtworkRepository;
import static com.ramiart.admin.galleryartwork.application.GalleryArtworkModels.*;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.*;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.stereotype.Repository;

@Repository
public class JdbcGalleryArtworkRepository implements GalleryArtworkRepository {
    private final JdbcClient jdbc;
    public JdbcGalleryArtworkRepository(JdbcClient jdbc){this.jdbc=jdbc;}
    private static final String SELECT="""
        select g.id,g.artwork_id,g.revision,g.status,g.visible,g.title,g.course_id,c.code course_code,c.name course_name,c.active course_active,
        g.audience_label,g.medium,g.description,g.media_asset_id,a.public_path image_url,a.original_file_name,a.mime_type,a.file_size,a.width,a.height,a.expires_at,
        g.alt_text,g.student_consent_id,case when sc.status='ACTIVE' and sc.expires_on is not null and sc.expires_on < (statement_timestamp() at time zone 'Asia/Seoul')::date then 'EXPIRED' else sc.status end consent_status,s.student_name,cp.revision policy_revision,g.consent_exemption_reason,
        g.featured,g.featured_order,g.version,g.updated_at,g.published_at
        from gallery_artwork g left join course c on c.id=g.course_id left join media_asset a on a.id=g.media_asset_id
        left join student_consent sc on sc.id=g.student_consent_id left join student s on s.id=sc.student_id
        left join consent_policy cp on cp.id=sc.consent_policy_id
        """;
    @Override public Optional<Stored> find(UUID artwork,String status){return jdbc.sql(SELECT+" where g.artwork_id=:artwork and g.status=:status order by g.revision desc limit 1").param("artwork",artwork).param("status",status).query(this::map).optional();}
    @Override public Optional<Stored> findRevision(UUID id){return jdbc.sql(SELECT+" where g.id=:id").param("id",id).query(this::map).optional();}
    @Override public Page list(String keyword,List<UUID> courses,List<String> states,String featured,String sort,int page,int size){
        String filter=" where 1=1 ";Map<String,Object> params=new HashMap<>();
        if(keyword!=null&&!keyword.isBlank()){filter+=" and coalesce(d.title,p.title,'') ilike :keyword ";params.put("keyword","%"+keyword+"%");}
        if(courses!=null&&!courses.isEmpty()){filter+=" and coalesce(d.course_id,p.course_id) in (:courses) ";params.put("courses",courses);}
        if(featured!=null&& !featured.equals("ALL")){filter+=" and "+(featured.equals("FEATURED")?"coalesce(p.featured,false)=true":"coalesce(p.featured,false)=false");}
        if(states!=null&&!states.isEmpty()){List<String> clauses=new ArrayList<>();for(String state:states){switch(state){case "DRAFT_ONLY"->clauses.add("(p.id is null and d.id is not null)");case "PUBLISHED_VISIBLE"->clauses.add("(p.id is not null and p.visible)");case "PUBLISHED_HIDDEN"->clauses.add("(p.id is not null and not p.visible)");case "HAS_DRAFT"->clauses.add("d.id is not null");default->throw new GalleryArtworkException("VALIDATION_ERROR");}}filter+=" and ("+String.join(" or ",clauses)+")";}
        String base="""
          from (select distinct artwork_id from gallery_artwork) ids
          left join gallery_artwork d on d.artwork_id=ids.artwork_id and d.status='DRAFT'
          left join gallery_artwork p on p.artwork_id=ids.artwork_id and p.status='PUBLISHED'
          """;
        String order=switch(sort){case "PUBLISHED_DESC"->"coalesce(p.published_at,d.updated_at) desc,ids.artwork_id";case "TITLE_ASC"->"coalesce(d.title,p.title) asc nulls last,ids.artwork_id";case "FEATURED_ORDER_ASC"->"p.featured_order asc nulls last,ids.artwork_id";default->"greatest(coalesce(d.updated_at,'-infinity'),coalesce(p.updated_at,'-infinity')) desc,ids.artwork_id";};
        var countQuery=jdbc.sql("select count(*) "+base+filter);params.forEach(countQuery::param);long total=countQuery.query(Long.class).single();
        var idsQuery=jdbc.sql("select ids.artwork_id "+base+filter+" order by "+order+" limit :limit offset :offset");params.forEach(idsQuery::param);List<UUID> ids=idsQuery.param("limit",size).param("offset",page*size).query(UUID.class).list();
        List<ListItem> result=ids.stream().map(this::item).toList();return new Page(result,new PageInfo(page,size,total,(int)Math.ceil(total/(double)size)));
    }
    private ListItem item(UUID id){Stored d=find(id,"DRAFT").orElse(null),p=find(id,"PUBLISHED").orElse(null);Stored v=d==null?p:d;
        return new ListItem(id,v==null?null:v.title(),v==null||v.courseId()==null?null:new Course(v.courseId(),v.courseCode(),v.courseName(),v.courseActive()),v==null?null:v.medium(),v==null||v.mediaAssetId()==null?null:new Media(v.mediaAssetId(),v.imageUrl(),"READY"),p==null?null:new PublishedSummary(p.revision(),p.visible(),p.publishedAt(),p.featured(),p.featuredOrder()),d==null?null:new DraftSummary(d.revision(),publishable(d),d.updatedAt(),d.featured()),List.of("VIEW","EDIT"));}
    @Override public UUID create(UUID artwork,int revision,UUID actor,Content c,UUID based){UUID id=UUID.randomUUID();jdbc.sql("""
        insert into gallery_artwork(id,artwork_id,revision,status,based_on_revision_id,title,course_id,audience_label,medium,description,media_asset_id,alt_text,student_consent_id,consent_exemption_reason,visible,featured,featured_order,created_by)
        values(:id,:artwork,:revision,'DRAFT',:based,:title,:course,:audience,:medium,:description,:asset,:alt,:consent,:reason,:visible,:featured,:order,:actor)
        """).param("id",id).param("artwork",artwork).param("revision",revision).param("based",based).param("title",c.title()).param("course",c.courseId()).param("audience",blank(c.audienceLabel())).param("medium",blank(c.medium())).param("description",blank(c.description())).param("asset",c.mediaAssetId()).param("alt",blank(c.altText())).param("consent",c.studentConsentId()).param("reason",blank(c.consentExemptionReason())).param("visible",Boolean.TRUE.equals(c.visible())).param("featured",Boolean.TRUE.equals(c.featured())).param("order",c.featuredOrder()).param("actor",actor).update();return id;}
    @Override public int update(UUID id,Write w){return jdbc.sql("""
        update gallery_artwork set title=:title,course_id=:course,audience_label=:audience,medium=:medium,description=:description,media_asset_id=:asset,alt_text=:alt,student_consent_id=:consent,consent_exemption_reason=:reason,visible=:visible,featured=:featured,featured_order=:order,version=version+1
        where id=:id and status='DRAFT' and version=:version
        """).param("title",blank(w.title())).param("course",w.courseId()).param("audience",blank(w.audienceLabel())).param("medium",blank(w.medium())).param("description",blank(w.description())).param("asset",w.mediaAssetId()).param("alt",blank(w.altText())).param("consent",w.studentConsentId()).param("reason",blank(w.consentExemptionReason())).param("visible",Boolean.TRUE.equals(w.visible())).param("featured",Boolean.TRUE.equals(w.featured())).param("order",w.featuredOrder()).param("id",id).param("version",w.version()).update();}
    @Override public boolean consentValid(UUID id){return id!=null&&Boolean.TRUE.equals(jdbc.sql("select exists(select 1 from student_consent where id=:id and policy_type='MEDIA_PUBLICATION' and status='ACTIVE' and (expires_on is null or expires_on >= (statement_timestamp() at time zone 'Asia/Seoul')::date))").param("id",id).query(Boolean.class).single());}
    @Override public boolean owner(UUID id){return Boolean.TRUE.equals(jdbc.sql("select exists(select 1 from admin_user_role ur join admin_role r on r.id=ur.admin_role_id join admin_user u on u.id=ur.admin_user_id where ur.admin_user_id=:id and r.code='OWNER' and u.status='ACTIVE')").param("id",id).query(Boolean.class).single());}
    @Override public void replaceReferences(UUID id,UUID asset){jdbc.sql("delete from media_asset_reference where owner_type='GALLERY_ARTWORK' and owner_id=:id and field_name='artworkImage' and reference_state='DRAFT'").param("id",id).update();if(asset!=null){if(!Boolean.TRUE.equals(jdbc.sql("select exists(select 1 from media_asset where id=:id and status='READY')").param("id",asset).query(Boolean.class).single()))throw new GalleryArtworkException("GALLERY_MEDIA_INVALID");jdbc.sql("insert into media_asset_reference(asset_id,owner_type,owner_id,field_name,reference_state) values(:asset,'GALLERY_ARTWORK',:id,'artworkImage','DRAFT') on conflict do nothing").param("asset",asset).param("id",id).update();}}
    @Override public void publish(UUID artwork,UUID draft,long version,UUID actor,Content c){jdbc.sql("select id from gallery_artwork where status='PUBLISHED' order by artwork_id for update").query(UUID.class).list();Stored d=findRevision(draft).orElseThrow(()->new GalleryArtworkException("GALLERY_NOT_FOUND"));if(d.version()!=version)throw new GalleryArtworkException("GALLERY_VERSION_CONFLICT");
        if(d.visible()&&d.featured()&&Boolean.TRUE.equals(jdbc.sql("select exists(select 1 from gallery_artwork where status='PUBLISHED' and visible and featured and featured_order=:n and artwork_id<>:artwork)").param("n",d.featuredOrder()).param("artwork",artwork).query(Boolean.class).single()))throw new GalleryArtworkException("GALLERY_FEATURED_ORDER_CONFLICT");
        jdbc.sql("update gallery_artwork set status='ARCHIVED' where artwork_id=:artwork and status='PUBLISHED'").param("artwork",artwork).update();
        jdbc.sql("update gallery_artwork set consent_exemption_reason=:reason,student_consent_id=:consent,status='PUBLISHED',published_by=:actor,published_at=statement_timestamp(),version=version+1 where id=:id and status='DRAFT' and version=:version")
                .param("reason",blank(c.consentExemptionReason())).param("consent",c.studentConsentId()).param("actor",actor).param("id",draft).param("version",version).update();
        jdbc.sql("update media_asset_reference set reference_state='PUBLISHED' where owner_type='GALLERY_ARTWORK' and owner_id=:id and field_name='artworkImage'").param("id",draft).update();}
    @Override public List<ListItem> previewList(){return jdbc.sql("select distinct artwork_id from gallery_artwork where status='DRAFT'").query(UUID.class).list().stream().map(this::item).toList();}
    @Override public List<PublicArtwork> publicList(List<String> codes,Boolean featured,int page,int size){String sql="select g.artwork_id,c.code,g.audience_label,g.title,g.medium,g.description,a.public_path,g.alt_text,g.featured,g.featured_order,g.published_at from gallery_artwork g join course c on c.id=g.course_id join media_asset a on a.id=g.media_asset_id left join student_consent sc on sc.id=g.student_consent_id where g.status='PUBLISHED' and g.visible and ((g.student_consent_id is not null and sc.status='ACTIVE' and (sc.expires_on is null or sc.expires_on >= (statement_timestamp() at time zone 'Asia/Seoul')::date)) or (g.student_consent_id is null and g.consent_exemption_reason is not null))";if(codes!=null&&!codes.isEmpty())sql+=" and c.code in (:codes)";if(featured!=null)sql+=" and g.featured=:featured";sql+=" order by g.featured desc,g.featured_order asc nulls last,g.published_at desc,g.artwork_id desc limit :limit offset :offset";var q=jdbc.sql(sql);if(codes!=null&&!codes.isEmpty())q.param("codes",codes);if(featured!=null)q.param("featured",featured);return q.param("limit",size).param("offset",page*size).query((r,n)->new PublicArtwork(r.getObject(1,UUID.class),r.getString(2),r.getString(3),r.getString(4),r.getString(5),r.getString(6),r.getString(7),r.getString(8),r.getBoolean(9),(Integer)r.getObject(10),r.getTimestamp(11).toInstant())).list();}
    @Override public long publicCount(List<String> codes,Boolean featured){String sql="select count(*) from gallery_artwork g join course c on c.id=g.course_id left join student_consent sc on sc.id=g.student_consent_id where g.status='PUBLISHED' and g.visible and ((g.student_consent_id is not null and sc.status='ACTIVE' and (sc.expires_on is null or sc.expires_on >= (statement_timestamp() at time zone 'Asia/Seoul')::date)) or (g.student_consent_id is null and g.consent_exemption_reason is not null))";if(codes!=null&&!codes.isEmpty())sql+=" and c.code in (:codes)";if(featured!=null)sql+=" and g.featured=:featured";var q=jdbc.sql(sql);if(codes!=null&&!codes.isEmpty())q.param("codes",codes);if(featured!=null)q.param("featured",featured);return q.query(Long.class).single();}
    @Override public List<Consent> consentOptions(String keyword,int page,int size){String k=keyword==null?"":keyword.trim().toLowerCase().replaceAll("\\s+","");return jdbc.sql("""
        select sc.id, left(s.student_name,1)||'**' masked, coalesce(course.name,'미배정') course_name,cp.revision,sc.consented_at,sc.expires_on,sc.status,sc.version
        from student_consent sc join student s on s.id=sc.student_id join consent_policy cp on cp.id=sc.consent_policy_id
        left join lateral(select c.name from student_schedule_assignment a join schedule_slot ss on ss.id=a.schedule_slot_id join class_group g on g.id=ss.class_group_id join course c on c.id=g.course_id where a.student_id=s.id and a.effective_from <= current_date and (a.effective_to is null or a.effective_to >= current_date) order by a.effective_from desc limit 1) course on true
        where sc.policy_type='MEDIA_PUBLICATION' and sc.status='ACTIVE' and (sc.expires_on is null or sc.expires_on >= (statement_timestamp() at time zone 'Asia/Seoul')::date)
        and (:keyword='' or s.student_name_search like '%'||:keyword||'%') order by sc.consented_at desc,sc.id limit :size offset :offset
        """).param("keyword",k).param("size",size).param("offset",page*size).query((r,n)->new Consent(r.getObject(1,UUID.class).toString(),r.getString(2),r.getString(3),r.getInt(4),r.getObject(5,java.time.OffsetDateTime.class).toInstant(),r.getObject(6,java.time.LocalDate.class)==null?null:r.getObject(6,java.time.LocalDate.class).atStartOfDay(java.time.ZoneId.of("Asia/Seoul")).toInstant(),r.getString(7),r.getLong(8))).list();}
    @Override public Claim claim(String scope,UUID key,String hash){int n=jdbc.sql("insert into idempotency_record(scope,idempotency_key,request_hash,expires_at) values(:scope,:key,:hash,statement_timestamp()+interval '24 hours') on conflict do nothing").param("scope",scope).param("key",key).param("hash",hash).update();if(n==1)return new Claim(true,null);var row=jdbc.sql("select request_hash,state,resource_id from idempotency_record where scope=:scope and idempotency_key=:key for update").param("scope",scope).param("key",key).query((r,i)->new Object[]{r.getString(1),r.getString(2),r.getObject(3,UUID.class)}).single();if(!hash.equals(row[0]))throw new GalleryArtworkException("IDEMPOTENCY_KEY_REUSED");if(!"COMPLETED".equals(row[1])||row[2]==null)throw new GalleryArtworkException("IDEMPOTENCY_IN_PROGRESS");return new Claim(false,(UUID)row[2]);}
    @Override public void complete(String scope,UUID key,UUID resource,int status){jdbc.sql("update idempotency_record set state='COMPLETED',resource_id=:resource,response_status=:status where scope=:scope and idempotency_key=:key").param("resource",resource).param("status",status).param("scope",scope).param("key",key).update();}
    @Override public int maxRevision(UUID id){return jdbc.sql("select coalesce(max(revision),0) from gallery_artwork where artwork_id=:id").param("id",id).query(Integer.class).single();}
    private Stored map(ResultSet r,int n)throws SQLException{return new Stored(r.getObject("id",UUID.class),r.getObject("artwork_id",UUID.class),r.getInt("revision"),r.getString("status"),r.getBoolean("visible"),r.getString("title"),r.getObject("course_id",UUID.class),r.getString("course_code"),r.getString("course_name"),r.getBoolean("course_active"),r.getString("audience_label"),r.getString("medium"),r.getString("description"),r.getObject("media_asset_id",UUID.class),r.getString("image_url"),r.getString("original_file_name"),r.getString("mime_type"),r.getLong("file_size"),r.getInt("width"),r.getInt("height"),r.getObject("expires_at",java.time.OffsetDateTime.class)==null?null:r.getObject("expires_at",java.time.OffsetDateTime.class).toInstant(),r.getString("alt_text"),r.getObject("student_consent_id",UUID.class),r.getString("consent_status"),r.getString("student_name")==null?null:r.getString("student_name").substring(0,1)+"**",(Integer)r.getObject("policy_revision"),r.getString("consent_exemption_reason"),r.getBoolean("featured"),(Integer)r.getObject("featured_order"),r.getLong("version"),r.getTimestamp("updated_at").toInstant(),r.getTimestamp("published_at")==null?null:r.getTimestamp("published_at").toInstant());}
    private static String blank(String s){return s==null||s.isBlank()?null:s.trim();}
    private static boolean publishable(Stored s){return s.title()!=null&&s.courseId()!=null&&s.audienceLabel()!=null&&s.medium()!=null&&s.description()!=null&&s.mediaAssetId()!=null&&s.altText()!=null&&((s.consentId()!=null&&"ACTIVE".equals(s.consentStatus()))||(s.consentId()==null&&s.exemptionReason()!=null));}
}
