package com.ramiart.admin.tuition.application;

import com.ramiart.admin.auth.application.AuditRecorder;
import com.ramiart.admin.auth.application.AuditRecorder.Event;
import com.ramiart.admin.tuition.application.StudentTuitionAssignmentModels.*;
import com.ramiart.admin.tuition.application.StudentTuitionAssignmentRepository.*;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.time.Clock;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.*;
import org.springframework.security.core.Authentication;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Isolation;
import org.springframework.transaction.annotation.Transactional;

@Service
public class StudentTuitionAssignmentService {
    public record MutationResult(Map<String,Object> data,int status) {}
    private static final ZoneId STUDIO=ZoneId.of("Asia/Seoul");
    private final StudentTuitionAssignmentRepository repository; private final AuditRecorder audit; private final Clock clock;
    public StudentTuitionAssignmentService(StudentTuitionAssignmentRepository repository,AuditRecorder audit,Clock clock){this.repository=repository;this.audit=audit;this.clock=clock;}
    @Transactional(readOnly=true,isolation=Isolation.REPEATABLE_READ)
    public Map<String,Object> list(UUID studentId,Authentication auth){requireRead(auth);Student s=student(studentId,false);LocalDate today=LocalDate.now(clock.withZone(STUDIO));List<Assignment> all=repository.assignments(studentId);
        return Map.of("student",Map.of("studentId",s.id(),"name",s.name(),"status",s.status()),"groups",Map.of("active",all.stream().filter(a->state(a,today).equals("ACTIVE")).map(a->view(a,today)).toList(),"scheduled",all.stream().filter(a->state(a,today).equals("SCHEDULED")).map(a->view(a,today)).toList(),"ended",all.stream().filter(a->state(a,today).equals("ENDED")).map(a->view(a,today)).toList()));}
    @Transactional(readOnly=true,isolation=Isolation.REPEATABLE_READ)
    public CandidateResult candidates(UUID studentId,LocalDate from,Authentication auth){requireRead(auth);student(studentId,false);LocalDate date=from==null?LocalDate.now(clock.withZone(STUDIO)):from;int count=repository.scheduleCount(studentId,date);List<PolicyOption> options=count==0?List.of():repository.policyOptions(date,count);return new CandidateResult(date,count,count==0?"NO_ACTIVE_SCHEDULE":options.isEmpty()?"POLICY_ITEM_NOT_FOUND":null,options);}
    @Transactional
    public MutationResult create(UUID studentId,Write raw,UUID actor,UUID key,Metadata meta){Write w=normalize(raw);String scope=actor+":STUDENT_TUITION_CREATE:"+studentId;var claim=repository.claim(scope,key,digest("POST:"+studentId+":"+w));if(!claim.claimed())return new MutationResult(view(repository.assignment(claim.resourceId(),false).orElseThrow(()->new StudentTuitionAssignmentException("STUDENT_TUITION_ASSIGNMENT_NOT_FOUND")),LocalDate.now(clock.withZone(STUDIO))),200);
        Student s=student(studentId,true);if(!"ACTIVE".equals(s.status()))throw new StudentTuitionAssignmentException("STUDENT_STATUS_NOT_ASSIGNABLE");if(!repository.policyItemPublished(w.policyItemId()))throw new StudentTuitionAssignmentException("TUITION_POLICY_ITEM_NOT_FOUND");
        int actual=repository.scheduleCount(studentId,w.effectiveFrom());int expected=policyCount(w.policyItemId());if(actual!=expected)throw new StudentTuitionAssignmentException("TUITION_LESSON_COUNT_MISMATCH",Map.of("expected",expected,"actual",actual));List<Assignment> conflicts=repository.overlaps(studentId,w.effectiveFrom(),w.effectiveTo(),null);if(!conflicts.isEmpty())throw periodConflict(conflicts);
        UUID id=UUID.randomUUID();repository.insert(id,studentId,w,actor);record(actor,meta,"STUDENT_TUITION_ASSIGNMENT_CREATED",id,Map.of("studentId",studentId,"policyItemId",w.policyItemId()));repository.complete(scope,key,id,201);return new MutationResult(view(repository.assignment(id,false).orElseThrow(),LocalDate.now(clock.withZone(STUDIO))),201);}
    @Transactional
    public Map<String,Object> update(UUID id,Update raw,UUID actor,UUID key,Metadata meta){if(raw==null||raw.version()<0)throw new StudentTuitionAssignmentException("VALIDATION_ERROR");if(raw.effectiveFrom()==null||raw.effectiveTo()!=null&&raw.effectiveTo().isBefore(raw.effectiveFrom()))throw new StudentTuitionAssignmentException("VALIDATION_ERROR");String reason=raw.overrideReason()==null?null:raw.overrideReason().trim();if(raw.overrideAmount()!=null&&(raw.overrideAmount()<0||raw.overrideAmount()>999_999_999_999L)||((raw.overrideAmount()==null)!=(reason==null))||reason!=null&&(reason.length()<5||reason.length()>200))throw new StudentTuitionAssignmentException("TUITION_OVERRIDE_REASON_REQUIRED");Write w=new Write(null,raw.effectiveFrom(),raw.effectiveTo(),raw.overrideAmount(),reason);String scope=actor+":STUDENT_TUITION_UPDATE:"+id;var claim=repository.claim(scope,key,digest("PUT:"+id+":"+raw));if(!claim.claimed())return view(repository.assignment(id,false).orElseThrow(()->new StudentTuitionAssignmentException("STUDENT_TUITION_ASSIGNMENT_NOT_FOUND")),LocalDate.now(clock.withZone(STUDIO)));
        Assignment current=repository.assignment(id,true).orElseThrow(()->new StudentTuitionAssignmentException("STUDENT_TUITION_ASSIGNMENT_NOT_FOUND"));if(current.version()!=raw.version())throw new StudentTuitionAssignmentException("STUDENT_TUITION_VERSION_CONFLICT");Student owner=student(current.studentId(),true);if(!"ACTIVE".equals(owner.status())&&(!w.effectiveFrom().equals(current.from())||!Objects.equals(w.overrideAmount(),current.overrideAmount())||!Objects.equals(w.overrideReason(),current.overrideReason())||w.effectiveTo()==null||current.to()!=null&&w.effectiveTo().isAfter(current.to())))throw new StudentTuitionAssignmentException("STUDENT_STATUS_NOT_ASSIGNABLE");
        validateLessonCount(current.studentId(),w.effectiveFrom(),current.policyItemId());
        if(current.billingCount()>0&&!Objects.equals(raw.overrideAmount(),current.overrideAmount()))throw new StudentTuitionAssignmentException("TUITION_ASSIGNMENT_BILLED_PERIOD");
        if(current.earliestBilledMonth()!=null&&(w.effectiveFrom().isAfter(current.earliestBilledMonth())||(w.effectiveTo()!=null&&w.effectiveTo().isBefore(current.latestBilledMonth()))))throw new StudentTuitionAssignmentException("TUITION_ASSIGNMENT_BILLED_PERIOD");
        List<Assignment> conflicts=repository.overlaps(current.studentId(),w.effectiveFrom(),w.effectiveTo(),id);if(!conflicts.isEmpty())throw periodConflict(conflicts);
        if(repository.update(id,new Update(w.effectiveFrom(),w.effectiveTo(),w.overrideAmount(),w.overrideReason(),raw.version()),w.overrideReason(),actor)!=1)throw new StudentTuitionAssignmentException("STUDENT_TUITION_VERSION_CONFLICT");record(actor,meta,"STUDENT_TUITION_ASSIGNMENT_UPDATED",id,Map.of("previousVersion",raw.version()));repository.complete(scope,key,id,200);return view(repository.assignment(id,false).orElseThrow(),LocalDate.now(clock.withZone(STUDIO)));}
    private int policyCount(UUID item){return repository.policyItemCount(item).orElseThrow(()->new StudentTuitionAssignmentException("TUITION_POLICY_ITEM_NOT_FOUND"));}
    private void validateLessonCount(UUID studentId,LocalDate at,UUID item){int expected=policyCount(item),actual=repository.scheduleCount(studentId,at);if(expected!=actual)throw new StudentTuitionAssignmentException("TUITION_LESSON_COUNT_MISMATCH",Map.of("expected",expected,"actual",actual));}
    private static StudentTuitionAssignmentException periodConflict(List<Assignment> values){List<Map<String,Object>> conflicts=values.stream().map(a->{Map<String,Object> value=new LinkedHashMap<>();value.put("assignmentId",a.id());value.put("effectiveFrom",a.from());value.put("effectiveTo",a.to());return value;}).toList();return new StudentTuitionAssignmentException("STUDENT_TUITION_PERIOD_CONFLICT",Map.of("conflicts",conflicts));}
    private Student student(UUID id,boolean lock){return repository.student(id,lock).orElseThrow(()->new StudentTuitionAssignmentException("STUDENT_NOT_FOUND"));}
    private void requireRead(Authentication auth){if(auth==null||!auth.getAuthorities().stream().anyMatch(a->a.getAuthority().equals("STUDENT_READ"))||!auth.getAuthorities().stream().anyMatch(a->a.getAuthority().equals("TUITION_POLICY_READ")))throw new StudentTuitionAssignmentException("STUDENT_TUITION_READ_DENIED");}
    private void record(UUID actor,Metadata m,String action,UUID id,Map<String,Object> details){audit.record(new Event(clock.instant(),m.requestId(),"MGT-STUDENT-TUITION-ASSIGN","OPERATION","ADMIN",actor,null,action,"STUDENT_TUITION_ASSIGNMENT",id,"SUCCESS",null,m.ip(),m.userAgent(),details));}
    private static Write normalize(Write w){if(w==null||w.policyItemId()==null||w.effectiveFrom()==null||w.effectiveTo()!=null&&w.effectiveTo().isBefore(w.effectiveFrom()))throw new StudentTuitionAssignmentException("VALIDATION_ERROR");Long amount=w.overrideAmount();String reason=w.overrideReason()==null?null:w.overrideReason().trim();if(amount!=null&&(amount<0||amount>999_999_999_999L)||((amount==null)!=(reason==null))||reason!=null&&(reason.length()<5||reason.length()>200))throw new StudentTuitionAssignmentException("TUITION_OVERRIDE_REASON_REQUIRED");return new Write(w.policyItemId(),w.effectiveFrom(),w.effectiveTo(),amount,reason);}
    private static String state(Assignment a,LocalDate today){return a.from().isAfter(today)?"SCHEDULED":a.to()!=null&&a.to().isBefore(today)?"ENDED":"ACTIVE";}
    private static Map<String,Object> view(Assignment a,LocalDate today){String status=state(a,today);Map<String,Object> policy=Map.of("policyId",a.policyId(),"year",a.policyYear(),"revision",a.revision(),"itemId",a.policyItemId(),"lessonCountPerWeek",a.count(),"baseAmount",a.baseAmount());Map<String,Object> impact=new LinkedHashMap<>();impact.put("earliestBilledMonth",a.earliestBilledMonth()==null?null:a.earliestBilledMonth().toString().substring(0,7));impact.put("latestBilledMonth",a.latestBilledMonth()==null?null:a.latestBilledMonth().toString().substring(0,7));impact.put("billingCount",a.billingCount());Map<String,Object> row=new LinkedHashMap<>();row.put("assignmentId",a.id());row.put("policy",policy);row.put("overrideAmount",a.overrideAmount());row.put("overrideReason",a.overrideReason());row.put("effectiveAmount",a.overrideAmount()==null?a.baseAmount():a.overrideAmount());row.put("effectiveFrom",a.from());row.put("effectiveTo",a.to());row.put("status",status);row.put("billedImpact",impact);row.put("version",a.version());row.put("actions",Map.of("canEdit",true,"canEnd",a.to()==null||a.to().isAfter(today)));return row;}
    private static String digest(String v){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(v.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}
}
